### ISSUE TITLE
Error when inspecting wall post with photo

### ISSUE THREAD

**Issue by Wixty** [negezor/vk-io#118]
#### What version of `vk-io` are you using?
v4.0.0-rc.6

#### What version of Node.js are you using?
v10.12.0

#### What did you do?
Получение polling обновлений группы
Пост с фото, отлаживаем контекст через `util.inspect(ctx)`

#### What did you expect to happen?
Вывод полей объекта

#### What was the actual result?
Ошибка, стак трейс ниже

```
Handle polling update error: TypeError: Cannot read property 'find' of null
    at sizeTypes.map.sizeType (/var/www/*/node_modules/vk-io/lib/index.js:3167:44)
    at Array.map (<anonymous>)
    at PhotoAttachment.getSizes (/var/www/*/node_modules/vk-io/lib/index.js:3167:22)
    at PhotoAttachment.get smallPhoto [as smallPhoto] (/var/www/*/node_modules/vk-io/lib/index.js:3137:25)
    at copyParams (/var/www/*/node_modules/vk-io/lib/index.js:268:30)
    at PhotoAttachment.[inspectCustomData] (/var/www/*/node_modules/vk-io/lib/index.js:3171:12)
    at PhotoAttachment.[nodejs.util.inspect.custom] (/var/www/*/node_modules/vk-io/lib/index.js:2578:31)
    at formatValue (internal/util/inspect.js:453:31)
    at formatProperty (internal/util/inspect.js:1028:11)
    at formatArray (internal/util/inspect.js:855:17)
    at formatRaw (internal/util/inspect.js:680:14)
    at formatValue (internal/util/inspect.js:471:10)
    at formatProperty (internal/util/inspect.js:1028:11)
    at formatRaw (internal/util/inspect.js:684:11)
    at formatValue (internal/util/inspect.js:471:10)
    at inspect (internal/util/inspect.js:193:10)
    at WallAttachment.[nodejs.util.inspect.custom] (/var/www/*/node_modules/vk-io/lib/index.js:2580:39)
    at formatValue (internal/util/inspect.js:453:31)
    at formatProperty (internal/util/inspect.js:1028:11)
    at formatRaw (internal/util/inspect.js:684:11)
    at formatValue (internal/util/inspect.js:471:10)
    at inspect (internal/util/inspect.js:193:10)
```

Ошибка тут:
https://github.com/negezor/vk-io/blob/21b6501992c7fc35d327056eb4680c9577813067/src/structures/attachments/photo.mjs#L170-L178

По дефолту sizes = null, в getSizes по идее нужна проверка.
https://github.com/negezor/vk-io/blob/21b6501992c7fc35d327056eb4680c9577813067/src/structures/attachments/photo.mjs#L159-L161
Но судя по применению функции в модуле, она обязана что-то возвращать.

Возможно, данная ошибка характерна именно для случая "пост с фото", т.к. там поля sizes в payload нет вообще. Прилагаю инспект аттача фото у поста:
```json
{
"type":"photo",
"ownerId":-172780313,
"id":456239027,
"accessKey":"*",
"$filled":true,
"payload": { 
    "id":456239027,
    "album_id":-7,
    "owner_id":-172780313,
    "user_id":100,
    "photo_75":"https://pp.userapi.com/c851336/v851336691/28a13/ZTQ0lPKm8MI.jpg",
    "photo_130":"https://pp.userapi.com/c851336/v851336691/28a14/e2eDJW0bHB4.jpg",
    "photo_604":"https://pp.userapi.com/c851336/v851336691/28a15/yi6AXpqX038.jpg",
    "width":331,
    "height":384,
    "text":"",
    "date":1539993248,
    "access_key":"*"
}}
```

**Comment by Wixty** [comment]
Для FHD фото
```json
{
"type":"photo",
"ownerId":-172780313,
"id":456239041,
"accessKey":"*",
"$filled":true,
"payload":{
    "id":456239041,
    "album_id":-7,
    "owner_id":-172780313,
    "user_id":100,
    "photo_75":"https://pp.userapi.com/c851336/v851336352/285af/KQJfcRUowwU.jpg",
    "photo_130":"https://pp.userapi.com/c851336/v851336352/285b0/HvEhsJ3SB2g.jpg",
    "photo_604":"https://pp.userapi.com/c851336/v851336352/285b1/YHnfjBMAcsA.jpg",
    "photo_807":"https://pp.userapi.com/c851336/v851336352/285b2/eT5mHGnmZa4.jpg",
    "photo_1280":"https://pp.userapi.com/c851336/v851336352/285b3/dVL2oCm2uqI.jpg",
    "photo_2560":"https://pp.userapi.com/c851336/v851336352/285b4/nVNmkSWMiuM.jpg",
    "width":1920,
    "height":1080,
    "text":"",
    "date":1539995854,
    "post_id":17,
    "access_key":"*"
}}
```

**Comment by Wixty** [comment]
Поправил #119, протестировал, теперь работает корректно.

**Comment by negezor** [comment]
Какая версия API используется? Потому что если она ниже 5.77, то и будут данные проблемы. Но библиотека стремится использовать самую последнюю версию.

**Comment by Wixty** [comment]
Точно, в одной из групп дефолтная стояла, 5.50. Ещё удивился, почему поведение не во всех группах аналогичное. Поиски в истории версий апи по слову 'sizes' ничего не дали.
Значит прикрутим автообновление версии до версии библиотеки, спасибо.
