### ISSUE TITLE
Нет поддержки двухэтапной авторизации

### ISSUE THREAD

**Issue by ily294** [negezor/vk-io#20]
Нет поддержки двухэтапной авторизации. При попытке войти в аккаунт возвращается ошибка:
```
{AuthError: Failed to get token
    at new AuthError (E:\Projects\nodejs\VkAuth\node_modules\vk-io\errors\auth.js:27:10)
    at request.then (E:\Projects\nodejs\VkAuth\node_modules\vk-io\auth\direct.js:163:11)
    at tryCatcher (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\Projects\nodejs\VkAuth\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5) name: 'AuthError', code: 'AUTHORIZATION_FAILED' }
```

**Comment by negezor** [comment]
На данный момент нет реализации, но есть в планах. Просто на текущий момент сложно сказать как лучше сделать.
