### ISSUE TITLE
Unhandled rejection ApiError: Invalid hash

### ISSUE THREAD

**Issue by DQvsRA** [negezor/vk-io#24]
I trying to upload a photo to album but get an error

API.call("photos.getWallUploadServer", { group_id: vkInfo.groupID })
.then((resp)=> {
    console.log(resp);
    vk.upload.wall(
    {
        source: postPhotoURL,
        uploadUrl: resp.upload_url
    });
})

nhandled rejection ApiError: Invalid hash
    at new ApiError (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/vk-io/errors/api.js:40:10)
    at Api._error (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/vk-io/api/index.js:287:11)
    at vk.request.then (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/vk-io/api/index.js:229:17)
    at tryCatcher (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by negezor** [comment]
Better upload directly:
```javascript
vk.upload.wall({
  source: {
    value: postPhotoURL,
    options: {
      filename: 'my-filename.jpg',
      contentType: 'image/jpeg'
    }
  }
});
```

**Comment by DQvsRA** [comment]
The problem is that I need to upload multiple images for single post. And I doing it in a loop, and each time upload.wall asking for getWallUploadServer. How can I do multiple uploads for single post in a proper way?

**Comment by DQvsRA** [comment]
So i found what is a problem - bluebird.

Image Другая ошибка: TypeError: Catch statement predicate: expecting an object but got [object Undefined]
    at apiRejection (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:10:27)
    at Promise.caught.Promise.catch (/home/dqvsra/Documents/Projects/SPRCLSTR/node_modules/bluebird/js/release/promise.js:98:24)

**Comment by DQvsRA** [comment]
Could you please remove it completely

**Comment by negezor** [comment]
This is a VK problem, the file did not load. 😞
