### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by el9in** [negezor/vk-io#317]
node_modules/vk-io/lib/index.js:8509
        this.callbackService = options.callbackService
                                       ^

TypeError: Cannot read property 'callbackService' of undefined
    at new VK (/home/el9in/node_modules/vk-io/lib/index.js:8509:40)
    at Object.<anonymous> (/home/el9in/callback.js:24:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by el9in** [comment]
И вопрос про random_id в messages.send, теперь его нужно заполнять в ручную?

**Comment by MrZillaGold** [comment]
[Почитайте про изменения в 4 версии библиотеки](https://negezor.github.io/vk-io/ru/guide/migration-to-v4.html#breaking-%D1%81hanges), там написано и про random_id и про то, что теперь **hear** вынесен в отдельный модуль из-за этого и ошибка.

**Comment by el9in** [comment]
Спасибо за ответ.
