### ISSUE TITLE
vk.updates.hear is not a function что делать?

### ISSUE THREAD

**Issue by ogmishanya** [negezor/vk-io#320]
TypeError: vk.updates.hear is not a function
    at Object.<anonymous> (F:\Bot Cracken\bot.js:43:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by ogmishanya** [comment]
Спасибо!

**Comment by nitreojs** [comment]
закройте issue, если это помогло

**Comment by isinkin** [comment]
@negezor, предлагаю закрыть issue.
