### ISSUE TITLE
callBack service isnt defined

### ISSUE THREAD

**Issue by qukallon1337** [negezor/vk-io#324]
root@ubuntu-32gb-nbg1-1:~/bot# node start.js
/root/bot/node_modules/vk-io/lib/index.js:8510
        this.callbackService = options.callbackService
                                       ^

TypeError: Cannot read property 'callbackService' of undefined
    at new VK (/root/bot/node_modules/vk-io/lib/index.js:8510:40)
    at Object.<anonymous> (/root/bot/start.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `last` |
| `node`                             | `12` |

**Comment by negezor** [comment]
Дубликат https://github.com/negezor/vk-io/issues/317
