### ISSUE TITLE
Ошибка старта

### ISSUE THREAD

**Issue by CsSave** [negezor/vk-io#329]
`/root/VKBot/node_modules/vk-io/lib/index.js:8510
        this.callbackService = options.callbackService
                                       ^

TypeError: Cannot read property 'callbackService' of undefined
    at new VK (/root/VKBot/node_modules/vk-io/lib/index.js:8510:40)
    at Object.<anonymous> (/root/VKBot/index.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
`

**Comment by negezor** [comment]
Дубликат https://github.com/negezor/vk-io/issues/317
