### ISSUE TITLE
TypeError: Cannot read property '__scene' of undefined

### ISSUE THREAD

**Issue by tenwiq** [negezor/vk-io#353]
node index
TypeError: Cannot read property '__scene' of undefined
    at SceneContext.updateSession (/home/demeff/node_modules/@vk-io/scenes/lib/index.js:131:64)
    at new SceneContext (/home/demeff/node_modules/@vk-io/scenes/lib/index.js:31:14)
    at /home/demeff/node_modules/@vk-io/scenes/lib/index.js:361:29
    at /home/demeff/node_modules/vk-io/lib/index.js:7839:15
    at nextDispatch (/home/demeff/node_modules/middleware-io/lib/index.js:52:40)
    at /home/demeff/node_modules/middleware-io/lib/index.js:52:67
    at /home/demeff/node_modules/vk-io/lib/index.js:7840:15
    at nextDispatch (/home/demeff/node_modules/middleware-io/lib/index.js:52:40)
    at /home/demeff/node_modules/middleware-io/lib/index.js:52:67
    at /home/demeff/node_modules/vk-io/lib/index.js:7840:15
    at nextDispatch (/home/demeff/node_modules/middleware-io/lib/index.js:52:40)
    at /home/demeff/node_modules/middleware-io/lib/index.js:52:67
    at /home/demeff/node_modules/vk-io/lib/index.js:7840:15
    at nextDispatch (/home/demeff/node_modules/middleware-io/lib/index.js:52:40)
    at /home/demeff/node_modules/middleware-io/lib/index.js:52:67
    at /home/demeff/node_modules/vk-io/lib/index.js:7840:15

**Comment by isinkin** [comment]
Мб код покажете?

**Comment by negezor** [comment]
Судя по всему не установлена сессия.

**Comment by tenwiq** [comment]
Помогло с установкой сессией. Спасибо
