### ISSUE TITLE
Ошибка вызова метода wall.post 

### ISSUE THREAD

**Issue by dimkadenisov** [negezor/vk-io#384]
#### What did you do?
Ознакомившись с [issue#99](https://github.com/negezor/vk-io/issues/99), пытаюсь опубликовать запись с прикрепленными фотографиями на стене сообщества, в котором являюсь администратором.

#### What did you expect to happen?

Ожидалось, что код, приведенный ниже, будет публиковать запись на стене сообщества.

```javascript
import { VK } from 'vk-io';

export default async (req, res) => {
  const {
    query: { access_token, photos },
  } = req;

  const photosUrls = photos.split(',');

  const vk = new VK({
    token: access_token,
  });
  const attachments = await Promise.all(
    photosUrls.map((url) =>
      vk.upload.wallPhoto({
        source: {
          value: url,
        },
      }),
    ),
  );

  const post = await vk.api.wall.post({
    attachments,
    ownerId: `-${process.env.NEXT_PUBLIC_VK_CLUB_ID}`,
  });

  console.log(post);

  res.statusCode = 200;
  res.json({ result: true });
};
```

#### What was the actual result?

В реальности же получается следующая ошибка:

```
APIError: Code №15 - Access denied: no access to call this method
    at SequentialWorker.execute (/Users/fatality/work/mood-finder/node_modules/vk-io/lib/index.js:1548:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 15,
  params: [
    { key: 'method', value: 'wall.post' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.126' },
    {
      key: 'attachments',
      value: 'photo29628523_457243804_c5aa69308619660cbe,photo29628523_457243801_6dd631086ef2ed4395,photo29628523_457243802_dc220d9f7521c00e40,photo29628523_457243803_f3bbe8bbb857708b51,photo29628523_457243805_1bf9d78f8c791723bc,photo29628523_457243806_d2776c57de788a195d'
    },
    { key: 'ownerId', value: '-197904398' }
  ]
}
```

#### Additional Info

Если свериться с [официальной документацией](https://vk.com/dev/errors) по кодам ошибок, то получается следующее:

> 15 - Доступ запрещён. 
> Убедитесь, что Вы используете верные идентификаторы, и доступ к контенту для текущего пользователя есть в полной версии сайта.

Однако сложность в том, что я точно уверен в корректности таких параметров как `ownerId`, `access_token`, а также в том, что при запросе токена указал все нужные `scope`. 

Токен получаю на клиенте, используя Implicit Flow авторизацию. Потом передаю токен на сервер.

Вот пруф того, что у приложения есть все нужные scope:
<img width="554" alt="Screenshot 2020-12-12 at 03 28 02" src="https://user-images.githubusercontent.com/32514564/101967761-00d3af80-3c2d-11eb-82ce-ab782dddf3e8.png">

Также хочется отметить, что [здесь](https://vk.com/dev/wall.post) в интерфейсе тестирования запросов все отрабатывает корректно, и запись публикуется.

Благодарю вас за разработку прекрасного инструмента, а также заранее спасибо за ответ и помощь!

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.1.1` |
| `node`                             | `14.15.1` |
| `TypeScript`                       | `X.Y.Z` |
| `yarn` or `npm`                    | `1.22.10` |

**Comment by dimkadenisov** [comment]
Закрыл issue, потому что из-за моей невнимательности я не заметил того, что при авторизации, если указать свой redirect_uri, невозможно будет вызывать методы, доступные только для Standalone-приложений.
