### ISSUE TITLE
Бот группы не отправляет изображение в беседе

### ISSUE THREAD

**Issue by marsell72** [negezor/vk-io#415]
Взял пример из репозитория:
```
hearCommand('cat', async (context) => {
	await Promise.all([
		context.send('Wait for the uploads awesome 😻'),

		context.sendPhotos({
			value: 'https://loremflickr.com/400/300/'
		})
	]);
});
```
В личных сообщениях работает, но в беседе только пишет: Wait for the uploads awesome 😻
Как быть?

**Comment by negezor** [comment]
Какие-нибудь ошибки?

**Comment by marsell72** [comment]
> Какие-нибудь ошибки?

Вот
```
APIError: Code №1 - Unknown error occurred
    at SequentialWorker.execute (.\node_modules\vk-io\lib\index.js:1613:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
```
