### ISSUE TITLE
ошибка при загрузке больших видео 

### ISSUE THREAD

**Issue by lNavigatoRl** [negezor/vk-io#458]
При попытке загрузить большой видео файл(более 100мб) с помощью 
```node
vk.upload.video({
        album_id: 0,
        group_id: id,
        name: name,
        description: desc,
        is_private: "0",
        wallpost: "1",
        no_comments: "0",
        repeat: "0",
        source: {
            value: './downloads/video.mp4'
        }
    })
```
Возникает ошибка спустя +/- 20 секунд: 
```html
file:///home/admin/bot_node/test/bot/node_modules/node-fetch/src/index.js:56
			const error = new AbortError('The operation was aborted.');
			              ^

AbortError: The operation was aborted.
    at abort (file:///home/admin/bot_node/test/bot/node_modules/node-fetch/src/index.js:56:18)
    at AbortSignal.abortAndFinalize (file:///home/admin/bot_node/test/bot/node_modules/node-fetch/src/index.js:75:4)
    at AbortSignal.dispatchEvent (/home/admin/bot_node/test/bot/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/admin/bot_node/test/bot/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/admin/bot_node/test/bot/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at Timeout.<anonymous> (/home/admin/bot_node/test/bot/node_modules/vk-io/lib/index.js:4797:54)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  type: 'aborted'
}
```

Насколько я понимаю, это связанно с таймаутом. Добавление `timeout: 60e3` не дает никакого эффекта. 
С видео размерами <100мб такой ошибки нет

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.4.0` |
| `node`                             | `15.12.0` |
| `TypeScript`                       | `no` |
| `yarn` or `npm`                    | `7.6.3` |

**Comment by negezor** [comment]
Возможно просто этого таймаута не хватает. Стоит попробовать его увеличить.
```ts
vk.upload.video({
    album_id: 0,
    group_id: id,
    name: name,
    description: desc,
    is_private: "0",
    wallpost: "1",
    no_comments: "0",
    repeat: "0",
    source: {
        // 5 min
        timeout: 60_000 * 5
        value: './downloads/video.mp4'
    }
});
```

**Comment by DudoMan** [comment]
У меня тоже ошибка(( маленькие файлы норм, а вот с большими траблы!
Значение менял timeout: 180000 / 60_000 * 5 / 60_000 * 10

Ничего не помогает

**Comment by VladRossohin** [comment]
Для меня сработал вариант передавать value внутри массива values, в таком случае timeout работает: 

```
vk.upload.video({
        album_id: 0,
        group_id: id,
        name: name,
        description: desc,
        is_private: "0",
        wallpost: "1",
        no_comments: "0",
        repeat: "0",
        source: {
            values: [{
                value: './downloads/video.mp4'
            }]
        }
    })
```

Скорее всего причина в нормализации данных внутри библиотеки.
