### ISSUE TITLE
(vk-io-question) Ошибка

### ISSUE THREAD

**Issue by SpeaxLp** [negezor/vk-io#460]
Запускаю код, у меня вот такое:
```
D:\bot-vk-js\public\node_modules\vk-io-question\lib\index.js:17
                this.isTimeout = isTimeout ?? false;
                                            ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\bot-vk-js\public\test.js:4:29)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```
Node: v12.18.3

**Comment by SpeaxLp** [comment]
Не тому написал
