### ISSUE TITLE
Вываливается ошибка после завершения программы с execute/executes 

### ISSUE THREAD

**Issue by ColdSpirit0** [negezor/vk-io#484]
#### What did you do?
Вызвал executes, где запрашиваются данные, к которым нет доступа
```js
(async function executeTest() {
    let result = await executes({
        api: vk.api,
        method: "likes.isLiked",
        queue: [
            { // https://vk.com/photo1_456264771 ok
                owner_id: 1,
                item_id: 456264771,
                type: "photo"
            },
            { // https://vk.com/photo1_1234 no access
                owner_id: 1,
                item_id: 1234,
                type: "photo"
            },
            { // https://vk.com/photo1_215187843 ok
                owner_id: 1,
                item_id: 215187843,
                type: "photo"
            },
        ]
    }).catch(e => console.log("executes got error:", e))

    console.log("-------------------")
    console.log("Got result", result)
    console.log("-------------------")

})().catch(e => console.log("executeTest got error:", e))
```

#### What did you expect to happen?
После завершения программы нет ошибок, нет вообще никаких неподхваченных сообщений. А в result все данные получены, не считая тех, к которым нет доступа.

#### What was the actual result?
После завершения выводится ошибка. Если убрать .map(...), то будет предупреждение, что где-то пропустили асинхронную ошибку.
```
> npx ts-node src/index.ts

-------------------
Got result {
  response: [ { liked: 0, copied: 0 }, false, { liked: 0, copied: 0 } ],     
  errors: [
    ExecuteError: Code №15 - Access denied: access restriction
        at projectdir\node_modules\vk-io\lib\index.js:1676:73     
        at Array.map (<anonymous>)
        at SequentialWorker.execute (projectdir\node_modules\vk-io\lib\index.js:1676:57)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: 15,
      params: [],
      method: 'likes.isLiked'
    }
  ]
}
-------------------
projectdir\node_modules\vk-io\lib\index.js:1676
                errors: (response.execute_errors || []).map((error) => (new ExecuteError(error)))
                                                        ^
ExecuteError: Code №15 - Access denied: access restriction
    at projectdir\node_modules\vk-io\lib\index.js:1676:73
    at Array.map (<anonymous>)
    at SequentialWorker.execute (projectdir\node_modules\vk-io\lib\index.js:1676:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {  
  code: 15,
  params: [],
  method: 'likes.isLiked'
}
The terminal process "C:\Windows\System32\cmd.exe /d /c npm run start" terminated with exit code: 1.
```

#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.5.2` |
| `node`                             | `17.2.0` |
| `TypeScript`                       | `4.5.4` |
| `yarn` or `npm`                    | `8.1.4` |

**Comment by ColdSpirit0** [comment]
![KSLysLaXZb](https://user-images.githubusercontent.com/16982207/165697894-8f1c5ce8-6bd4-4ba3-a18d-6728b96f2767.png)
**Возможно** проблема в resolveExecuteTask - мне непонятно, зачем он резолвит и реджектит отдельные таски, если ошибки и так собираются в кучу; и эвейтов под эти таски нигде нет.
