### ISSUE TITLE
Не получается прикрепить несколько фото к одному сообщению (EXCEEDED_MAX_FILES)

### ISSUE THREAD

**Issue by hramtsov13** [negezor/vk-io#497]
#### What did you do?
Отправляю 2 айтема внутри одного аттачмента 

#### What did you expect to happen?
Ожидаю, что фото отправятся в одном сообщении

#### What was the actual result?
<img width="815" alt="image" src="https://user-images.githubusercontent.com/57592116/177048234-ac5f23cf-0aa9-4490-93b5-2680e231fb89.png">

#### Additional Info
Делаю все (как мне кажется) согласно доке https://negezor.github.io/vk-io/ru/guide/upload.html#%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%82 

`await vk.api.messages.sendMessageEventAnswer({
      event_id: context.eventId,
      user_id: context.userId,
      peer_id: context.peerId,
      conversation_message_ids: context.conversationMessageId,
      event_data: JSON.stringify({
        type: 'show_snackbar',
        text: `Хэй, ${user.first_name}, вот инфа по курсу`,
      }),
    });

    const attachment = await vk.upload.messagePhoto({
      source: {
        values: [
          {
            value: 'attachments/images/course-level-up.jpeg',
            // Название файла (нужно в основном для загрузки в документы)
            filename: 'course.jpeg',
            // Тип загружаемого контента
            contentType: 'image/jpeg',
            // Размер файла в битах, обязательно при загрузке через ReadableStream или если невозможно получить длину другим способом
            contentLength: fs.statSync('attachments/images/course-level-up.jpeg').size,
          },
          {
            value: 'attachments/images/useful/first/first-1.png',
            // Название файла (нужно в основном для загрузки в документы)
            filename: 'first.png',
            // Тип загружаемого контента
            contentType: 'image/png',
            // Размер файла в битах, обязательно при загрузке через ReadableStream или если невозможно получить длину другим способом
            contentLength: fs.statSync('attachments/images/useful/first/first-1.png').size,
          },
        ],
      },
    });

    await vk.api.messages.send({
      user_id: context.userId,
      peer_id: context.peerId,
      attachment,
      message: COURSE_MESSAGE,
      random_id: getRandomId(),
    });`

В итоге получаю ошибку 
`UploadError: The number of files uploaded has exceeded
    at Upload.conduct (/Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/vk-io/lib/index.js:8014:19)
    at Upload.messagePhoto (/Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/vk-io/lib/index.js:7556:36)
    at /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/bot.js:70:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/middleware-io/lib/index.js:280:9 {
  code: 'EXCEEDED_MAX_FILES'
}`

При этом, если прикреплять только одно фото, все работает ок
`
const attachment1 = await vk.upload.messagePhoto({
      source: {
        value: './attachments/images/course-level-up.jpeg',
      },
    });`

Не могу понять где я ошибся, pls help me!)
#### Versions

| package                            | version |
| ---------------------------------- | ------- |
| `vk-io`                            | `4.6.0` |
| `node`                             | `16.13.0` |
| `TypeScript`                       | `4.7.3` |
| `npm`                    | `8.1.Z` |
| `@vk-io/hear`          | `1.1.0` |

**Comment by negezor** [comment]
```js
const attachment = await vk.upload.messagePhoto([{
    source: {
        value: 'attachments/images/course-level-up.jpeg',
        // Название файла (нужно в основном для загрузки в документы)
        filename: 'course.jpeg',
        // Тип загружаемого контента
        contentType: 'image/jpeg',
        // Размер файла в битах, обязательно при загрузке через ReadableStream или если невозможно получить длину другим способом
        contentLength: fs.statSync('attachments/images/course-level-up.jpeg').size,
    },
}, {
    source: {
        value: 'attachments/images/useful/first/first-1.png',
        // Название файла (нужно в основном для загрузки в документы)
        filename: 'first.png',
        // Тип загружаемого контента
        contentType: 'image/png',
        // Размер файла в битах, обязательно при загрузке через ReadableStream или если невозможно получить длину другим способом
        contentLength: fs.statSync('attachments/images/useful/first/first-1.png').size,
    },
}]);
```

**Comment by hramtsov13** [comment]
@negezor Большое спасибо за оперативный ответ! Предложенный вами способ действительно не вызывает ошибку, о которой я писал ранее, однако, возникает другая ошибка(

`UploadError: Missing upload params
    at Upload.conduct (/Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/vk-io/lib/index.js:7994:19)
    at Upload.messagePhoto (/Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/vk-io/lib/index.js:7556:36)
    at /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/bot.js:64:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/middleware-io/lib/index.js:280:9 {
  code: 'MISSING_PARAMETERS'`

**Comment by negezor** [comment]
Я не сразу заметил использование контекст и напрямую `upload.messagePhoto()`, можно сделать так:
```js
await context.sendPhotos([
    {
        value: 'attachments/images/course-level-up.jpeg',
        filename: 'course.jpeg',
        contentType: 'image/jpeg',
        contentLength: fs.statSync('attachments/images/course-level-up.jpeg').size,
    },
    {
        value: 'attachments/images/useful/first/first-1.png',
        filename: 'first.png',
        contentType: 'image/png',
        contentLength: fs.statSync('attachments/images/useful/first/first-1.png').size,
    }
], {
    message: COURSE_MESSAGE,
});
```

**Comment by hramtsov13** [comment]
@negezor В моем случае сообщение, к которому я хочу прикрепить несколько фото, отправляется в ответ на клик по инлайновой колбэк кнопке, соответсвенно я слушаю нажатие на одну из колбэк кнопок 
```js

//Слушаем нажатие на колбэк кнопку
vk.updates.on('message_event', async (context, next) => {

  //В зависимости от типа кнопки выполняю некоторые действия 
  if (context.eventPayload.button_type === 'button_course') {

       //Отправляем уведомление с некоторым текстом
      await vk.api.messages.sendMessageEventAnswer({
            event_id: context.eventId,
            user_id: context.userId,
            peer_id: context.peerId,
            conversation_message_ids: context.conversationMessageId,
            event_data: JSON.stringify({
              type: 'show_snackbar',
              text: `Хэй, ${user.first_name}, вот инфа по курсу`,
            }),
          });
      
      const attachment = await vk.upload.messagePhoto([
            {
              source: {
                value: 'attachments/images/course-level-up.jpeg',
                filename: 'course.jpeg',
                contentType: 'image/jpeg',
                contentLength: fs.statSync('attachments/images/course-level-up.jpeg').size,
              },
            },
            {
              source: {
                value: 'attachments/images/useful/first/first-1.png',
                filename: 'first.png',
                contentType: 'image/png',
                contentLength: fs.statSync('attachments/images/useful/first/first-1.png').size,
              },
            },
      ]);
      
      //Отправляем само сообщение **именно через vk.api.messages.send**, так как context получаемый через 
     //vk.updates.on не имеет метода sendPhotos и выпадает ошибка мол is not a function
      await vk.api.messages.send({
            user_id: context.userId,
            peer_id: context.peerId,
            attachment: attachment,
            message: COURSE_MESSAGE,
            random_id: getRandomId(),
      });
  }
} 
```

Context.sendPhotos можно сделать через hearManager.hear() например, так как в этом контексте будет присутствовать метод sendPhotos/sendDocuments, но насколько я могу судить context, получаемый в `vk.updates.on('message_event', async (context, next) => {})` отличается и не имеет такого метода 

```
----- Bot Started -----
TypeError: context.sendPhotos is not a function
    at /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/bot.js:83:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/mikhailkhramtsov/Documents/verstka/my-projects/vk-bot/node_modules/middleware-io/lib/index.js:280:9
```

**Comment by negezor** [comment]
```js
//Слушаем нажатие на колбэк кнопку
vk.updates.on('message_event', async (context, next) => {

  //В зависимости от типа кнопки выполняю некоторые действия 
  if (context.eventPayload.button_type === 'button_course') {

       //Отправляем уведомление с некоторым текстом
      await vk.api.messages.sendMessageEventAnswer({
            event_id: context.eventId,
            user_id: context.userId,
            peer_id: context.peerId,
            conversation_message_ids: context.conversationMessageId,
            event_data: JSON.stringify({
              type: 'show_snackbar',
              text: `Хэй, ${user.first_name}, вот инфа по курсу`,
            }),
          });
      
      const attachments = await Promise.all([
		vk.upload.messagePhoto({
		  source: {
			value: 'attachments/images/course-level-up.jpeg',
			filename: 'course.jpeg',
			contentType: 'image/jpeg',
			contentLength: fs.statSync('attachments/images/course-level-up.jpeg').size,
		  },
		}),
		vk.upload.messagePhoto({
		  source: {
			value: 'attachments/images/useful/first/first-1.png',
			filename: 'first.png',
			contentType: 'image/png',
			contentLength: fs.statSync('attachments/images/useful/first/first-1.png').size,
		  },
		})
	  ]);
      
      //Отправляем само сообщение **именно через vk.api.messages.send**, так как context получаемый через 
     //vk.updates.on не имеет метода sendPhotos и выпадает ошибка мол is not a function
      await vk.api.messages.send({
            user_id: context.userId,
            peer_id: context.peerId,
            attachment: attachments,
            message: COURSE_MESSAGE,
            random_id: getRandomId(),
      });
  }
} 
```
Если файлы статичные, лучше их один раз загрузить в альбом группы например и переиспользовать их ID, чтобы не засорять лимит на загрузку файлов группы.

**Comment by hramtsov13** [comment]
@negezor Спасибо большое, ваше предложение эвейтить Promise.all рабочее!
