### ISSUE TITLE
Cannot find module 'bufferutil' , 'utf-8-validate'

### ISSUE THREAD

**Issue by WebKieth** [negezor/vk-io#50]
**What version of vk-io are you using?**
4 альфа

**What version of Node.js are you using?**
8.9.1

После установки последней альфы в лог browserify полетел лог ошибок зависимостей:

1я ненайденная зависимость:
[17:44:09] gulp-notify: [Error running Gulp] Cannot find module 'utf-8-validate' from '/home/casper/projects/extreme-art/node_modules/vk-io/node_modules/ws/lib'
./src/_scripts/main.js was browserified: 5.889s
[BS] Reloading files that match: *.js
[17:44:09] Browserify compile error: 
 Error: Cannot find module 'bufferutil' from '/home/casper/projects/extreme-art/node_modules/vk-io/node_modules/ws/lib'
    at /home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

2я ненайденная зависимость:
[17:44:09] gulp-notify: [Error running Gulp] Cannot find module 'bufferutil' from '/home/casper/projects/extreme-art/node_modules/vk-io/node_modules/ws/lib'
[17:44:10] Browserify compile error: 
 Error: Cannot find module 'bufferutil' from '/home/casper/projects/extreme-art/node_modules/vk-io/node_modules/ws/lib'
    at /home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/casper/projects/extreme-art/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

Ошибки вылетают парно. Откат на 3.2.0 исправил проблему. Версия сборщика browserify: ~13.0.1

**Comment by negezor** [comment]
Ну библиотека же не клиентская, а на сервер.

**Comment by WebKieth** [comment]
Ага, до меня не сразу дошло, поэтому я открыл новый issue
