### ISSUE TITLE
Обработчик description для market.add

### ISSUE THREAD

**Issue by vladislavmega** [negezor/vk-io#6]
используя 
`vk.api.market.add({
  owner_id: groupId,
  main_photo_id: photo[0].id,
  name: 'testTitile',
  description: description,
  category_id: 1,
  price: 123
});`

где description:
"УМБ Golden Dragon K80 Dual LED Light 20000 mAh
Всего лишь 10 лет назад любой телефон мог держать заряд больше недели, даже если вы каждый день звонили сотне человек. Однако телефонам не хватало функциональности и технологического прогресса &ndash; и он пришел. Теперь телефоны компактны и многофункциональны, но полностью заряженный смартфон едва ли прослужит вам больше суток при активном использовании.
Это не вызывает неудобств, пока рядом есть источник питания, но что делать, если вам предстоит провести весь день в пути или вы собираетесь на природу? Хорошим выходом с таких случаях будет купить универсальную мобильную батарею Golden Dragon K80 20000 mAh. Это самый надежный, компактный и удобный способ зарядить ваш гаджет без розетки.
УМБ Golden Dragon K80 20000 mAh &ndash; это мощный аккумулятор, рассчитанный на долгое использование. Например, с его помощью вы сможете полностью зарядить смартфон больше 5 раз, а планшет &ndash; больше 3. Кроме того, вы можете зарядить одновременно 3 гаджета &ndash; например, смартфон, планшет и плеер, ведь в этой модели доступны сразу 3 USB-порта. Выход на 1,5 и 2,1 ампер позволяют заряжать любой гаджет &ndash; от плееров, которые требуют 0,5 и больше ампер, до большинства планшетов, требующих 2 А на выходе.
Отдельным плюсом будет небольшой размер батареи (16,5х7х2 см), то есть она не больше стандартного планшета. Таким образом, вы сможете без проблем всегда носить ее с собой. Для зарядки УМБ предусмотрен USB-порт, который можно подключить к ПК или розетке с помощью переходника. Чтобы вы не упустили момент полной зарядки, предусмотрен показатель заряда &ndash; светящийся индикатор на корпусе, состоящий из 4 светодиодов. Каждый из них соответствует 25 % зарядки."

вк не создает товар и в ответ получаю 
`{ RequestError: 400 - "<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx/0.3.33</center>\r\n</body>\r\n</html>\r\n"
    at new RequestError (/Users/vladislav/4buy_parse/node_modules/vk-io/primary/errors.js:64:9)
    at request.then.catch (/Users/vladislav/4buy_parse/node_modules/vk-io/middleware/api.js:86:12)
    at tryCatcher (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/vladislav/4buy_parse/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
  name: 'RequestError',
  statusCode: 400,
  message: '400 - "<html>\\r\\n<head><title>400 Bad Request</title></head>\\r\\n<body bgcolor=\\"white\\">\\r\\n<center><h1>400 Bad Request</h1></center>\\r\\n<hr><center>nginx/0.3.33</center>\\r\\n</body>\\r\\n</html>\\r\\n"' }`

если же сократить description и убрать символы - то товар сохраняет.
Возможно перед отправкой на vkapi нужна дополнительная проверка, вырезание лишнего

**Comment by negezor** [comment]
А какие символы именно были вырезаны?
