### ISSUE TITLE
Ошибка "Could not log in"

### ISSUE THREAD

**Issue by T1MOXA** [negezor/vk-io#97]
Более часа назад я около десяти раз авторизовался через токен в течении пары минут.
После чего возможность авторизации пропала.
Ок, лимит на авторизации подумал я, закрыл доступ приложения для аккаунта и попытался создать новый токен, но столкнулся с ошибкой
{"error":"invalid_request","error_description":"Security Error"}
И уже более часа не могу ничего сделать.
Но это скорее всего трабл вк.

Сейчас я попытался авторизоваться через другое приложение указав лишь токен, но получил ошибку:
```
{ AuthError: Could not log in
    at ImplicitFlowUser.run (/root/bots/vk/node_modules/vk-io/lib/index.js:2983:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 'AUTHORIZATION_FAILED',
  name: 'AuthError',
  pageHtml: null,
  stackframes:
   [ { file_name: '/root/bots/vk/node_modules/vk-io/lib/index.js',
       line_number: 2983 },
     { file_name: null, line_number: null },
     { file_name: 'internal/process/next_tick.js', line_number: 228 } ] }
```

Может у меня лимит не на токен а на аккаунт или проблема в чем-то другом ?

**Comment by T1MOXA** [comment]
Проблему решил вписав логин пароль и ид другого приложения.
В чем проблема с прошлым пока так и не понял.

**Comment by T1MOXA** [comment]
Думаю это вопрос больше к ВК
